### 5. 난수 발생과 카운팅

In [5]:
import numpy as np

- seed 설정

In [6]:
np.random.seed(2023)
np.random.random(5)

array([0.3219883 , 0.89042245, 0.58805226, 0.12659609, 0.14134122])

- 데이터의 순서 바꾸기

In [7]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.random.shuffle(x)
x

array([7, 4, 3, 2, 8, 9, 1, 6, 0, 5])

- 데이터 샘플링

In [10]:
np.random.choice(5, 5, replace=False)

array([3, 4, 0, 2, 1])

In [11]:
x = np.random.randint(1, 100, 10)
x

array([64, 49, 33, 30, 50, 50, 50, 50, 54, 39])

In [12]:
np.random.choice(x, 5, replace=False)

array([50, 30, 33, 49, 39])

- 난수 생성

In [13]:
# random() - Uniform 분포, 0~1 사이의 값
np.random.random(10)

array([0.40615836, 0.62311131, 0.80221535, 0.09702613, 0.81625998,
       0.02808046, 0.01545164, 0.56690572, 0.59310305, 0.9147945 ])

In [18]:
# randint(low, high, N) - [low, high)
np.random.randint(1, 7, 10)

array([4, 5, 1, 5, 3, 5, 1, 6, 1, 3])

In [20]:
# normal(평균, 표준편차, N) - 정규분포
np.random.normal(170, 10, 10)

array([160.01620207, 176.03242369, 166.58776424, 169.65713669,
       183.31161153, 157.14453006, 175.5215289 , 180.92597031,
       187.72102631, 168.86258604])

In [21]:
# randn(N) - 표준정규분포 N(0,1)
np.random.randn(10)

array([-1.39798223, -0.38444907,  0.45366873, -1.01517303,  0.16824259,
       -1.26226678,  2.05878925, -0.67827947, -0.28298011,  1.98911223])

In [24]:
# binominal(시도횟수, 평균, N) - 이항분포 B(N, p)
np.random.binomial(10, 0.5, 20).reshape(4,5)

array([[5, 5, 6, 5, 3],
       [6, 5, 4, 4, 5],
       [6, 4, 5, 6, 4],
       [6, 6, 7, 3, 3]])

In [25]:
# 가설 검정: t-검정
# standard_t(자유도, N)
np.random.standard_t(2, 10)

array([-0.09617727, -0.39052728,  2.18562042,  5.56256461, -1.1668642 ,
        7.32407575,  0.16764095, -0.083235  , -0.33859361, -0.38122265])

In [33]:
np.random.binomial(1, 0.5, 10)

array([1, 0, 1, 0, 1, 1, 0, 0, 0, 1])

In [38]:
np.mean(np.random.randint(1, 7, 100))

3.57

In [56]:
rate = np.random.normal(0, 0.01, 5)
rate

array([-0.00881216,  0.00395546,  0.02243496, -0.00876514, -0.00075965])

In [57]:
price = 10000
price = price + price * rate[0]
int(np.round(price))

9912

In [60]:
price = 10000
for i in range(5):
    price = price * (1 + rate[i])
    price = int(np.round(price))
    print(price, end=' ')

9912 9951 10174 10085 10077 

In [62]:
np.random.seed(2023)
rate = np.random.normal(0, 0.01, 250)
rate[:5]

array([ 0.00711674, -0.00324485, -0.01001871,  0.00236251, -0.0010216 ])

In [63]:
# 1. 리스트로 해결
price = 10000
price_list = []
for i in range(250):
    price = price * (1 + rate[i])
    price = int(np.round(price))
    price_list.append(price)

price_array = np.array(price_list)
price_array[-10:]

array([10814, 10893, 10674, 10645, 10588, 10724, 10739, 10686, 10691,
       10497])

In [64]:
# 2. 어레이로 해결
price_array2 = np.zeros(250, dtype=int)
price = 10000
for i in range(250):
    price = price * (1 + rate[i])
    price = int(np.round(price))
    price_array2[i] = price

price_array2[-10:]

array([10814, 10893, 10674, 10645, 10588, 10724, 10739, 10686, 10691,
       10497])

- 데이터 카운팅

In [65]:
dices = np.random.randint(1, 7, 100)
np.unique(dices)

array([1, 2, 3, 4, 5, 6])

In [67]:
indices, count = np.unique(dices, return_counts=True)
indices, count

(array([1, 2, 3, 4, 5, 6]), array([ 9, 24, 24, 13, 15, 15], dtype=int64))

In [75]:
np.sum(indices*count)/np.sum(count)

3.46

In [76]:
np.mean(dices)

3.46

In [77]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [80]:
index, count

(array(['a', 'b', 'c'], dtype='<U1'), array([2, 2, 1], dtype=int64))

In [81]:
np.bincount(dices, minlength=6)

array([ 0,  9, 24, 24, 13, 15, 15], dtype=int64)